#
# - Find libnl-tiny
# Find the native LIBNL-TINY includes and library
#
#  LIBNL-TINY_INCLUDE_DIRS - where to find netlink-generic.h, etc.
#  LIBNL-TINY_LIBRARIES    - List of libraries when using libnl-tiny.
#  LIBNL-TINY_FOUND        - True if libnl-tiny found.


IF (LIBNL-TINY_INCLUDE_DIRS)
  # Already in cache, be silent
  SET(LIBNL-TINY_FIND_QUIETLY TRUE)
ENDIF (LIBNL-TINY_INCLUDE_DIRS)

FIND_PATH(LIBNL-TINY_INCLUDE_DIR netlink-generic.h PATH_SUFFIXES libnl-tiny)
SET(LIBNL-TINY_NAMES nl-tiny)
FIND_LIBRARY(LIBNL-TINY_LIBRARY NAMES ${LIBNL-TINY_NAMES} )

# handle the QUIETLY and REQUIRED arguments and set LIBNL-TINY_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBNL-TINY DEFAULT_MSG LIBNL-TINY_LIBRARY LIBNL-TINY_INCLUDE_DIR)

IF(LIBNL-TINY_FOUND)
  SET( LIBNL-TINY_LIBRARIES ${LIBNL-TINY_LIBRARY} )
  SET( LIBNL-TINY_INCLUDE_DIRS ${LIBNL-TINY_INCLUDE_DIR} )
ELSE(LIBNL-TINY_FOUND)
  SET( LIBNL-TINY_LIBRARIES )
  SET( LIBNL-TINY_INCLUDE_DIRS )
ENDIF(LIBNL-TINY_FOUND)

MARK_AS_ADVANCED( LIBNL-TINY_LIBRARIES LIBNL-TINY_INCLUDE_DIRS )
